version: '3.8'
services:
  db:
    build: .
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  api:
    build: ./api_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db/bd_gas_nar

  frontend:
    build: ./dashboard_gas_nar/AdminPanel
    ports:
      - "3000:3000"
    depends_on:
      - api
